---
ansible_connection: winrm
ansible_port: 5986
ansible_winrm_server_cert_validation: ignore  # because we generate selfsign certificate 
ansible_winrm_transport: ntlm
ansible_user: ansible
ansible_password: P@ssw0rd
ansible_become: no
ansible_become_method: auto